apiVersion: apps/v1
kind: Deployment
metadata:
  name: oi56fd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oi56fd
  template:
    metadata:
      labels:
        app: oi56fd
    spec:
      containers:
      - image: okteto.dev/uoi56fd:latest
        name: oi56fd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "d869973f-39f5-4d25-ac57-22de9ab19fb6"
        - name: Vless_Path
          value: "/i84e"
        - name: Vmess_UUID
          value: "d869973f-39f5-4d25-ac57-22de9ab19fb6"
        - name: Vmess_Path
          value: "/uge1"
        - name: Share_Path
          value: "/share233"
