apiVersion: apps/v1
kind: Deployment
metadata:
  name: igfg8d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igfg8d
  template:
    metadata:
      labels:
        app: igfg8d
    spec:
      containers:
      - image: okteto.dev/igfg8d:latest
        name: igfg8d
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "greenmangaming.com"
        - name: Vless_UUID
          value: "10a35a1c-d723-4c22-88ac-481040845087"
        - name: Vless_Path
          value: "/fgsd"
        - name: Vmess_UUID
          value: "10a35a1c-d723-4c22-88ac-481040845087"
        - name: Vmess_Path
          value: "/rtfg"
        - name: Share_Path
          value: "/share233"
