apiVersion: apps/v1
kind: Deployment
metadata:
  name: kjlt9g
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kjlt9g
  template:
    metadata:
      labels:
        app: kjlt9g
    spec:
      containers:
      - image: okteto.dev/kjlt9g:latest
        name: kjlt9g
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "greenmangaming.com"
        - name: Vless_UUID
          value: "10a35a1c-d723-4c22-88ac-481040845087"
        - name: Vless_Path
          value: "/fgsd"
        - name: Vmess_UUID
          value: "10a35a1c-d723-4c22-88ac-481040845087"
        - name: Vmess_Path
          value: "/rtfg"
        - name: Share_Path
          value: "/share233"
