apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugde7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ugde7b
  template:
    metadata:
      labels:
        app: ugde7b
    spec:
      containers:
      - image: okteto.dev/ugde7b:latest
        name: iugde7b
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "d869973f-39f5-4d25-ac57-22de9ab19fb6"
        - name: Vless_Path
          value: "/i84e"
        - name: Vmess_UUID
          value: "d869973f-39f5-4d25-ac57-22de9ab19fb6"
        - name: Vmess_Path
          value: "/uge1"
        - name: Share_Path
          value: "/share233"
