apiVersion: apps/v1
kind: Deployment
metadata:
  name: kie85d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kie85d
  template:
    metadata:
      labels:
        app: kie85d
    spec:
      containers:
      - image: okteto.dev/kie85d:latest
        name: kie85d
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "lenskart.com"
        - name: Vless_UUID
          value: "78afc036-abdb-49fc-b2d9-f7e787b3552b"
        - name: Vless_Path
          value: "/e43wtr"
        - name: Vmess_UUID
          value: "78afc036-abdb-49fc-b2d9-f7e787b3552b"
        - name: Vmess_Path
          value: "/4jyrtg"
        - name: Share_Path
          value: "/share233"
