apiVersion: apps/v1
kind: Deployment
metadata:
  name: of5gh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: of5gh
  template:
    metadata:
      labels:
        app: of5gh
    spec:
      containers:
      - image: okteto.dev/of5gh:latest
        name: of5gh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "dbe94e43-6de8-4e76-8b14-592f43d78dee"
        - name: Vless_Path
          value: "/jmfe"
        - name: Vmess_UUID
          value: "dbe94e43-6de8-4e76-8b14-592f43d78dee"
        - name: Vmess_Path
          value: "/aifc"
        - name: Share_Path
          value: "/share233"
