apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgi87v
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jgi87v
  template:
    metadata:
      labels:
        app: jgi87v
    spec:
      containers:
      - image: okteto.dev/jgi87v:latest
        name: jgi87v
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "videvo.net"
        - name: Vless_UUID
          value: "9a5fe9f3-1d4b-4bdf-9442-1bef4e2c45f2"
        - name: Vless_Path
          value: "/hgdv"
        - name: Vmess_UUID
          value: "9a5fe9f3-1d4b-4bdf-9442-1bef4e2c45f2"
        - name: Vmess_Path
          value: "/iugf"
        - name: Share_Path
          value: "/share233"
