apiVersion: apps/v1
kind: Deployment
metadata:
  name: girl5g
spec:
  replicas: 1
  selector:
    matchLabels:
      app: girl5g
  template:
    metadata:
      labels:
        app: girl5g
    spec:
      containers:
      - image: okteto.dev/girl5g:latest
        name: girl5g
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "dbe94e43-6de8-4e76-8b14-592f43d78dee"
        - name: Vless_Path
          value: "/jmfe"
        - name: Vmess_UUID
          value: "dbe94e43-6de8-4e76-8b14-592f43d78dee"
        - name: Vmess_Path
          value: "/aifc"
        - name: Share_Path
          value: "/share233"
