apiVersion: v1
kind: Service
metadata:
  name: oi56fd
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "oi56fd"
    port: 8080
  selector:
    app: oi56fd
