apiVersion: v1
kind: Service
metadata:
  name: jgi87v
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "jgi87v"
    port: 8080
  selector:
    app: jgi87v
